name: simbadesketop
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: any
  cupertino_icons: ^1.0.5
  get: ^4.6.5
  shared_preferences: ^2.1.0
  connectivity_plus: 
  firebase_core: ^2.10.0
  firebase_messaging: ^14.4.1
  flutter_local_notifications: ^14.0.0+1
  path_provider: ^2.0.14
  url_strategy: ^0.2.0
  # country_code_picker: ^2.0.2

  dotted_border: ^2.0.0+3
  flutter_contacts: ^1.1.6
  azlistview: ^2.0.0
  pin_code_fields: ^7.4.0
  modal_bottom_sheet: ^2.1.2
  slide_to_confirm: ^1.1.0
  lottie: ^2.3.2
  expandable_bottom_sheet: ^1.1.1+1
  smooth_page_indicator: ^1.1.0
  image_picker: ^0.8.7+4
  country_code_picker: ^3.0.0
  camera: 
  http: ^0.13.6
  get_storage: ^2.1.1
  carousel_slider: ^4.2.1
  webview_flutter: ^4.2.0
  graphic: ^2.2.1
  face_camera: ^0.0.8
  flutter_svg: ^2.0.5
  device_preview: ^1.1.0
  flutter_html: ^3.0.0-alpha.6
  shimmer: ^2.0.0
  permission_handler: 
  share_plus: ^4.5.3
  screenshot: ^2.1.0
  gallery_saver: ^2.3.2
  modal_progress_hud_nsn: ^0.4.0
  phone_number: ^1.0.0
  path_drawing: ^1.0.1
  local_auth: ^2.1.6
  google_mlkit_barcode_scanning: ^0.6.0
  google_mlkit_face_detection: ^0.6.0
  cached_network_image: ^3.2.3
  flutter_secure_storage: ^8.0.0
  app_settings: ^4.2.0
  percent_indicator: ^4.2.3
  flutter_smart_dialog: ^4.9.0+6
  device_info_plus: ^8.2.2
  unique_identifier: ^0.3.0
  url_launcher: ^6.1.10
  flutter_inappwebview: ^5.7.2+3
  scroll_to_index: ^3.0.1
  fl_chart: ^0.64.0
  nb_utils: ^6.0.6
  pdf: ^3.10.4
  printing: ^5.11.0


dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/
    - assets/animationFile/
    - assets/payment/


  fonts:
    - family: Rubik
      fonts:
        - asset: assets/font/Rubik-Light.ttf
          weight: 300
        - asset: assets/font/Rubik-Regular.ttf
          weight: 400
        - asset: assets/font/Rubik-Medium.ttf
          weight: 500
        - asset: assets/font/Rubik-SemiBold.ttf
          weight: 600

# dependencies:
#   flutter:
#     sdk: flutter


#   # The following adds the Cupertino Icons font to your application.
#   # Use with the CupertinoIcons class for iOS style icons.
#   cupertino_icons: ^1.0.2
#   http: 
#   get:

# dev_dependencies:
#   flutter_test:
#     sdk: flutter

#   # The "flutter_lints" package below contains a set of recommended lints to
#   # encourage good coding practices. The lint set provided by the package is
#   # activated in the `analysis_options.yaml` file located at the root of your
#   # package. See that file for information about deactivating specific lint
#   # rules and activating additional ones.
#   flutter_lints: ^2.0.0

# # For information on the generic Dart part of this file, see the
# # following page: https://dart.dev/tools/pub/pubspec

# # The following section is specific to Flutter packages.
# flutter:

#   # The following line ensures that the Material Icons font is
#   # included with your application, so that you can use the icons in
#   # the material Icons class.
#   uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
